name: CI + CD

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣  checkout & setup
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }

      # 2️⃣  install deps & create tarball
      - run: npm ci
      #- run: npm run build         # keep if needed
      - run: |
          # ➊ use a fresh temporary file in /tmp
          tmpfile=$(mktemp -p /tmp release.XXXXXX.tgz)

          # ➋ create the archive from the repo root, WRITE to tmpfile
          tar -C . -czf "$tmpfile" --exclude=node_modules --exclude=.git .

          # ➌ move it back into the workspace so the scp step finds it
          mv "$tmpfile" release.tgz

          # ➍ make it world-readable so the scp container can read it
          chmod 644 release.tgz

      # 3️⃣  upload artefact + nginx conf
      - name: Upload release + nginx config
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          passphrase: ${{ secrets.VPS_KEY_PASSPHRASE }}
          source: "release.tgz,deploy/nginx/login.insightaiq.com.conf"
          target: "/home/brk/apps/insightaiq/deploy_tmp"
          overwrite: true # ensures old files are replaced

      # 4️⃣  remote deploy logic
      - name: Remote deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          passphrase: ${{ secrets.VPS_KEY_PASSPHRASE }}
          script: |
            set -e
            # make sure deploy_tmp exists (idempotent)
            mkdir -p /home/brk/apps/insightaiq/deploy_tmp

            cd /home/brk/apps/insightaiq

            # ----------- Nginx config -----------
            sudo mv deploy_tmp/login.insightaiq.com.conf /etc/nginx/sites-available/login.insightaiq.com
            sudo ln -sfn /etc/nginx/sites-available/login.insightaiq.com /etc/nginx/sites-enabled/login.insightaiq.com
            sudo nginx -t && echo "Nginx config OK"

            # ----------- Application release -----------
            cd releases
            ts=$(date +%Y%m%d%H%M%S)
            mkdir "$ts"
            tar xzf ../deploy_tmp/release.tgz -C "$ts"
            cd "$ts"
            npm ci --omit=dev --no-audit --no-fund
            ln -sfn /home/brk/apps/insightaiq/shared/.env .env
            ln -sfn "$PWD" /home/brk/apps/insightaiq/current

            # ----------- Service reloads -----------
            sudo pm2 startOrReload /home/brk/apps/insightaiq/current/ecosystem.config.js --update-env
            sudo nginx -t && sudo systemctl reload nginx

            # ----------- cleanup -----------
            rm -rf /home/brk/apps/insightaiq/deploy_tmp/*
